### ISSUE TITLE
Research methods readings

### ISSUE THREAD

**Issue by thin-lizard** [PugetSoundClinic-PIT/gig-policies#5]
**Research methods**
- designing qualitative and mixed method studies, case studies
- qualitative analysis - esp. in human subject / participatory research (interpreting interviews, focus groups, etc.)
- transparency and validity - in reporting and in working with research participants

**Potential readings**
- [Sociotechnical approaches to the study of information systems](https://experts.syr.edu/en/publications/sociotechnical-approaches-to-the-study-of-information-systems)
- Shilton, K., Moss, E., Gilbert, S. A., Bietz, M. J., Fiesler, C., Metcalf, J., Vitak, J., & Zimmer, M. (2021). Excavating awareness and power in data science: A manifesto for trustworthy pervasive data research. Big Data & Society, 8(2), 20539517211040760. https://doi.org/10.1177/20539517211040759
- Writing ethnographic fieldnotes - emerson fretz shaw - https://press.uchicago.edu/ucp/books/book/chicago/W/bo12182616.html

**Comment by nniiicc** [comment]
1. Doing of Ethnography 
2. Doing of interview-based research 
3. Case study research 
4. QCR - Qualitative Comparative Research

**Comment by thin-lizard** [comment]
- david baronov - conceptual foundations of social research methods 
- john searle - the social construction of reality
- nancy van house - information studies and STS
- christine halverson - what do theories do / cscw
